services:
  snack-vote-backend:
    image: whalebro/snack-vote-backend:1.3
    deploy:
      placement:
        constraints:
          - node.labels.type==back
    ports:
      - "4000:4000"
    networks:
      - snack-vote-network
    environment:
      DB_HOST_FILE: /run/secrets/DB_HOST
      DB_PORT: 3306
      DB_NAME: snackvote
      DB_USERNAME_FILE: /run/secrets/DB_USERNAME
      DB_PASSWORD_FILE: /run/secrets/DB_PASSWORD
      JWT_PRIVATE_KEY_FILE: /run/secrets/JWT_PRIVATE_KEY
      JWT_PRIVATE_KEY_EXP_TIME_FILE: /run/secrets/JWT_PRIVATE_KEY_EXP_TIME
      JWT_REFRESH_KEY_FILE: /run/secrets/JWT_REFRESH_KEY
      JWT_REFRESH_KEY_EXP_TIME_FILE: /run/secrets/JWT_REFRESH_KEY_EXP_TIME
      ROOT_EMAIL_FILE: /run/secrets/ROOT_EMAIL_FILE
      ROOT_PASSWORD_FILE: /run/secrets/ROOT_PASSWORD_FILE
      ROOT_NAME_FILE: /run/secrets/ROOT_NAME_FILE

    secrets:
      - DB_HOST
      - DB_USERNAME
      - DB_PASSWORD
      - JWT_PRIVATE_KEY
      - JWT_PRIVATE_KEY_EXP_TIME
      - JWT_REFRESH_KEY
      - JWT_REFRESH_KEY_EXP_TIME
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

  snack-vote-frontend:
    image: whalebro/snack-vote-frontend:1.3
    deploy:
      placement:
        constraints:
          - node.labels.type==front
    networks:
      - snack-vote-network
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - snack-vote-backend
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - /home/ubuntu/meta/nginx/sites.conf:/etc/nginx/conf.d/sites.conf
      - /home/ubuntu/meta/nginx/sites-enabled:/etc/nginx/sites-enabled

networks:
  snack-vote-network:

secrets:
  DB_HOST:
    external: true
  DB_USERNAME:
    external: true
  DB_PASSWORD:
    external: true
  JWT_PRIVATE_KEY:
    external: true
  JWT_PRIVATE_KEY_EXP_TIME:
    external: true
  JWT_REFRESH_KEY:
    external: true
  JWT_REFRESH_KEY_EXP_TIME:
    external: true
  REDIS_HOST:
    external: true
  REDIS_PORT:
    external: true
  ROOT_EMAIL:
    external: true
  ROOT_PASSWORD:
    external: true
  ROOT_NAME:
    external: true
