export const CONFIG_OPTIONS = 'CONFIG_OPTIONS';
export const PAGINATION_UNIT = 10;
export const PAGINATION_UNIT_COMMENTS = 30;
export const MAINPAGE_AGENDAS_UNIT = 6;
export const REFRESH_TOKEN_EXP_TIME = 15 * 24 * 60 * 60 * 1000;
