name: Server Test
on:
  push:
    branches:
      - main
      - vote
jobs:
  server-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        id: npm-cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: |
          cd server
          npm ci
      - name: run unit test
        run: |
          cd server
          npm run test
      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: build and push image
        uses: docker/build-push-action@v4
        with:
          context: server/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/snack-vote-backend:latest
