name: Server Test
on:
  push:
    branches:
      - main
      - vote
  pull_request:
    types: [closed]
jobs:
  server-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        id: npm-cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: |
          cd server
          npm ci
      - name: run unit test
        run: |
          cd server
          npm run test

  Build-and-push:
    runs-on: ubuntu-latest
    needs: server-unit
    if: github.ref_name == 'main' || ${{ contains(github.event.head_commit.message, 'version') }}
    steps:
      - uses: actions/checkout@v3

      - name: Extract version tag
        id: extract-version-tag
        run: |
          # Get the commit message
          commit_message="$(git log --format=%B -n 1)"

          # Extract the version tag using a regular expression
          version_tag="$(echo "$commit_message" | grep -o -E 'version:[0-9]+\.[0-9]+')"

          # Remove the "version:" prefix
          version_tag="${version_tag#version:}"

          # Set the output variable
          echo "::set-output name=version_tag::$version_tag"

      - name: docker login
        uses: docker/login-action@v2
        with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

      - name: backend build and push image
        uses: docker/build-push-action@v4
        with:
          context: server/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/snack-vote-backend:${{ steps.extract-version-tag.outputs.version_tag }}

      - name: frontend build and push image
        uses: docker/build-push-action@v4
        with:
          context: client/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/snack-vote-frontend:${{ steps.extract-version-tag.outputs.version_tag }}
