name: Server Test
on:
  push:
    branches:
      - main
      - vote
jobs:
  server-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        id: npm-cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: |
          cd server
          npm ci
      - name: run unit test
        run: |
          cd server
          npm run test
